version: '3.4'

services:
  webapp:
    container_name: ApiDoePlus
    image: apidoeplus
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    build:
      context: .
      dockerfile: Dockerfile